---
title: "app1.R"
output: html_document
date: "2025-06-30"
---
```{r}
#install.packages(c("knitr","caret","shiny", "randomForest", "plotly", "shinythemes", "shinydashboard", "shinycssloaders", "dashboardthemes", "DT", "plotly"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret)
library(shiny)
library(randomForest)
library(plotly)
library(shinythemes)
library(shinydashboard)
library(shinycssloaders)
library(dashboardthemes)
library(DT)
library(survminer)
library(survival)
library(plotly)
library(shapviz)
library(ClusterR)
library(data.table)
library(xgboost)
library(ggplot2)

customTheme <- shinyDashboardThemeDIY(
    
    ### general
    appFontFamily = "Serif"
    ,appFontColor = "rgb(0,0,0)"
    ,primaryFontColor = "rgb(0,0,0)"
    ,infoFontColor = "rgb(0,0,0)"
    ,successFontColor = "rgb(0,0,0)"
    ,warningFontColor = "rgb(0,0,0)"
    ,dangerFontColor = "rgb(0,0,0)"
    ,bodyBackColor = "rgb(255,255,255)"
    
    ### header
    ,logoBackColor = "#26C6DA"
    ,headerButtonBackColor = "#26C6DA"
    ,headerButtonIconColor = "rgb(0,0,0)"
    ,headerButtonBackColorHover = "rgb(255,255,255)"
    ,headerButtonIconColorHover = "rgb(0,0,0)"
    
    ,headerBackColor = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "#26C6DA"
        ,colorMiddle = "#26C6DA"
        ,colorEnd = "rgba(255,255,255)"
        ,colorStartPos = 0
        ,colorMiddlePos = 90
        ,colorEndPos = 100
    )
    ,headerBoxShadowColor = "black"
        ,headerBoxShadowSize = "2px 2px 2px"
    
    ### sidebar
    ,sidebarBackColor = cssGradientThreeColors(
        direction = "down"
        ,colorStart = "#26C6DA"
        ,colorMiddle = "#26C6DA"
        ,colorEnd = "rgba(255,255,255)"
        ,colorStartPos = 0
        ,colorMiddlePos = 50
        ,colorEndPos = 100
    )
    ,sidebarPadding = 0
    
    ,sidebarMenuBackColor = "transparent"
    ,sidebarMenuPadding = 0
    ,sidebarMenuBorderRadius = 0
    
    ,sidebarShadowRadius = "3px 5px 5px"
    ,sidebarShadowColor = "#aaaaaa"
        
    ,sidebarUserTextColor = "rgb(255,255,255)"
    
    ,sidebarSearchBackColor = "rgb(55,72,80)"
    ,sidebarSearchIconColor = "rgb(153,153,153)"
    ,sidebarSearchBorderColor = "#167682"
    
    ,sidebarTabTextColor = "rgb(0,0,0)"
    ,sidebarTabTextSize = 13
    ,sidebarTabBorderStyle = "none none solid none"
    ,sidebarTabBorderColor = "#167682"
    ,sidebarTabBorderWidth = 1
    
    ,sidebarTabBackColorSelected = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "rgba(250,250,250)"
        ,colorMiddle = "rgba(250,250,250)"
        ,colorEnd = "rgba(250,250,250)"
        ,colorStartPos = 0
        ,colorMiddlePos = 30
        ,colorEndPos = 100
    )
    ,sidebarTabTextColorSelected = "#167682"
    ,sidebarTabRadiusSelected = "0px 20px 20px 0px"
    
    ,sidebarTabBackColorHover = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "#167682"
        ,colorMiddle = "#167682"
        ,colorEnd = "#167682"
        ,colorStartPos = 0
        ,colorMiddlePos = 80
        ,colorEndPos = 100
    )
    ,sidebarTabTextColorHover = "rgb(255,255,255)"
    ,sidebarTabBorderStyleHover = "none none solid none"
    ,sidebarTabBorderColorHover = "rgb(75,126,151)"
    ,sidebarTabBorderWidthHover = 1
    ,sidebarTabRadiusHover = "0px 20px 20px 0px"
    
    ### boxes
    ,boxBackColor = "rgb(255,255,255)"
    ,boxBorderRadius = 5
    ,boxShadowSize = "0px 1px 1px"
    ,boxShadowColor = "rgba(0,0,0,.1)"
    ,boxTitleSize = 16
    ,boxDefaultColor = "#07272b"
    ,boxPrimaryColor = "#00CC66"
    ,boxInfoColor = "rgb(255, 252, 166)"
    ,boxSuccessColor = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "rgba(255,138,122,1)"
        ,colorMiddle = "rgba(252,110,90,1)"
        ,colorEnd = "rgba(212,90,70,1)"
        ,colorStartPos = 0
        ,colorMiddlePos = 30
        ,colorEndPos = 100)
    ,boxWarningColor = "rgb(244,156,104)"
    ,boxDangerColor = "rgb(255,88,55)"
    
    ,tabBoxTabColor = "#00CC66"
    ,tabBoxTabTextSize = 14
    ,tabBoxTabTextColor = "rgb(0,0,0)"
    ,tabBoxTabTextColorSelected = "rgb(0,0,0)"
    ,tabBoxBackColor = "rgb(212,90,70,1)"
    ,tabBoxHighlightColor = "rgba(212,90,70,1,1)"
    ,tabBoxBorderRadius = 5
    
    ### inputs
    ,buttonBackColor = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "#00CC66"
        ,colorMiddle = "#00CC66"
        ,colorEnd = "#00CC66"
        ,colorStartPos = 0
        ,colorMiddlePos = 60
        ,colorEndPos = 100)
    ,buttonTextColor = "rgb(250,250,250)"
    ,buttonBorderColor = "rgb(200,200,200)"
    ,buttonBorderRadius = 5
    
    ,buttonBackColorHover = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "rgba(255,255,255)"
        ,colorMiddle = "rgba(255,255,255)"
        ,colorEnd = "rgba(255,255,255)"
        ,colorStartPos = 0
        ,colorMiddlePos = 60
        ,colorEndPos = 100
    )
    ,buttonTextColorHover = "#00CC66"
    ,buttonBorderColorHover = "#00CC66"
    
    ,textboxBackColor = "rgb(255,255,255)"
    ,textboxBorderColor = "rgb(200,200,200)"
    ,textboxBorderRadius = 5
    ,textboxBackColorSelect = "rgb(245,245,245)"
    ,textboxBorderColorSelect = "rgb(200,200,200)"
    
    ### tables
    ,tableBackColor = "rgb(255,255,255)"
    ,tableBorderColor = "rgb(240,240,240)"
    ,tableBorderTopSize = 1
    ,tableBorderRowSize = 1

    
)

customLogo <- shinyDashboardLogoDIY(
    boldText = "TRIMel"
    ,mainText = "Tool for Risk Interpretation of Melanomas"
    ,textSize = 20
    ,badgeText = "v1.1"
    ,badgeTextColor = "black"
        ,badgeTextSize = 1
    ,badgeBackColor = "#2471A3"
        ,badgeBorderRadius = 3
    
)


#UI

# Define UI for application that draws a histogram
ui <- dashboardPage(
    
    dashboardHeader(title = customLogo, 
                    titleWidth = 500),
    
    dashboardSidebar(sidebarMenu(
        menuItem("TriMel", tabName = "trimel"),
        menuItem("TriMel_CSV",tabName="trimel_csv"),
        menuItem("TriMel_CSV with CT", tabName = "trimel_ct"),
        menuItem("Feature Comparison", tabName = "feature_compare")
        
    )),

    # Application title
    #titlePanel("TRIMel: Tool for Risk Interpretation of Melanomas"),

    # Sidebar with a slider input for number of bins 
    dashboardBody(customTheme,
                  tabItems(
                      tabItem(
                          tabName = "trimel",
                      fluidRow(
                          
                      
                          box(title = "Input Parameters", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          sliderInput("breslowdepth", "Breslow Depth (mm)", 0, 10, 0, step = 0.1),
                          selectInput("sex", "Sex", c("Select","Female", "Male"), selected = NULL),
                          numericInput("age", "Age", value = 50, min = 0, max = 102),
                          selectInput("ulceration", "Ulceration Status", c("Select","Absent", "Present"), selected = NULL),
                          numericInput("mitoticrate", "Mitotic Rate (mitoses / mm2)", value = 0, min = 0),
                          selectInput("location", "Skin Site", c("Select","Face, Head, or Neck", 
                                                            "Upper Limb or Shoulder", "Lower Limb or Hip", "Trunk"),
                                     selected = NULL),
                          selectInput("subtype", "Histologic Subtype", 
                                                        c("Select","Unspecified", "Nodular", 
                                                          "Superficial Spreading", "Acral Lentiginous", 
                                                          "Lentigo Maligna", "Desmoplastic"),
                                 selected = NULL),
                          
                          checkboxInput("ct", "Include CT Parameters"),
                          conditionalPanel(
                            condition = "input.ct == true",
                            numericInput("height", "Height in meters", value = 0 , min = 0),
                            numericInput("SMA", "Skeletal Muscle Area", value = 0 , min = 0),
                            numericInput("SFA", "Subcutaneous Fat Area", value = 0 , min = 0),
                            numericInput("VFA", "Visceral Fat Area", value = 0 , min = 0),
                            numericInput("IFA", "Intramuscular Fat Area", value = 0 , min = 0),
                            
                          ),
                          actionButton("go", "Submit")
                      ),

                             box(title = "Risk Classification:", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                                 plotOutput("class_plot")),
                      
                      box(title = "Summary:", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          textOutput("output_summary"))
                             
                      ),
                      ),
                      
                      tabItem(
                      tabName="trimel_csv",
                      box(title = "Input Parameters", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          fileInput("file_input","upload CSV file", accept = ".csv"),
                          downloadButton("download_csv","Download risk classification csv"),
                          br(),
                          br()
                          )
                      
                      ), 
                      tabItem(
                      tabName="trimel_ct",
                      fluidRow(
                        column(width = 3,
                          box(title = "Templates", width = NULL, status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          downloadButton("clinpath_template", "Download clinpath template csv"),
                          br(),
                          downloadButton("ct_template", "Download CT parameters template csv")
                          ),
                      
                      box(title = "Input Parameters", width = NULL, status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          fileInput("clinpath_input","upload clinical CSV file", accept = ".csv"),
                          
                          checkboxInput("ct", "Include CT Parameters"),
                          conditionalPanel(
                            condition = "input.ct == true",
                            fileInput("ct_input","upload CT CSV file", accept = ".csv")
                          ),
                          actionButton("combined_calc", "Calculate"),
                          br(),
                          downloadButton("download_combined","Download risk classification csv"),
                          br(),
                          br(),
                          )),
                        column(width = 9,
                        box(title = "Risk Comparison:", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                                 plotOutput("clin_ct_plot")))
                      )
                      ),
                      tabItem(
                        tabName="feature_compare",
                          column(width = 3,
                             box(title = "Templates", width = NULL, status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          downloadButton("clinpath_template2", "Download data template csv"),
                          ),

                          box(title = "Dataset", width = NULL, status = "primary", solidHeader = TRUE, collapsible = TRUE,
                          fileInput("feature_input","upload dataset file with additional features", accept = ".csv"),
                          actionButton("calc_feature", "Calculate")),
                          br(),
                          
                          downloadButton("download_feature","Download feature comparison csv"),
                          br(),
                          verbatimTextOutput("confusion1")
                          ),
                          column(width = 9,
                                 box(title = "Feature Comparison", status = "primary", solidHeader = TRUE, collapsible = TRUE,
                                     plotOutput("feature_num1"), plotOutput("feature_num2")),
                                 box(title = "Mortality Proportion", status = "primary", solidHeader = TRUE, plotOutput("cluster_bar")),
                                 verbatimTextOutput("confusion2")))
                          
                      

                      
    )))
    
server <- function(input, output) {
  
  
    observeEvent(input$go, {
        
        pt_data <- data.frame(
            "Age" = input$age,
            "Mitotic_Rate" = input$mitoticrate,
            "Breslow_Depth" = input$breslowdepth,
            "Ulceration" = 0,
            "Sex" = 0,
            "FaceHeadNeck" = 0,
            "UpperLimbShoulder" = 0,
            "LowerLimbHip" = 0,
            "Trunk" = 0,
            "Superficial_Spreading" = 0,
            "Nodular" = 0,
            "Lentigo_Maligna" = 0,
            "Acral_Lentiginous" = 0,
            "Desmoplastic" = 0
        )
        
        if (input$ulceration == "Present"){pt_data$Ulceration <- 1}
        if (input$sex == "Male"){pt_data$Sex <- 1}
        
        if (input$location == "Face, Head, or Neck"){pt_data$FaceHeadNeck <- 1}
        if (input$location == "Upper Limb or Shoulder"){pt_data$UpperLimbShoulder <- 1}
        if (input$location == "Lower Limb or Hip"){pt_data$LowerLimbHip <- 1}
        if (input$location == "Trunk"){pt_data$Trunk <- 1}
        
        if (input$subtype == "Nodular"){pt_data$Nodular <- 1}
        if (input$subtype == "Desmoplastic"){pt_data$Desmoplastic <- 1}
        if (input$subtype == "Superficial Spreading"){pt_data$Superficial_Spreading <- 1}
        if (input$subtype == "Acral Lentiginous"){pt_data$Acral_Lentiginous <- 1}
        if (input$subtype == "Lentigo Maligna"){pt_data$Lentigo_Maligna <- 1}
        
        scale <- readRDS("scaling_data.RData")
        
        scaled_pt_data <- predict(scale, pt_data)
        
        class_model <- readRDS("classification_model.RData")
        
        class <- as.character(predict(class_model, scaled_pt_data))
        

        
        if (input$breslowdepth <= 1 & class == "Low-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thin_lr_plot.RData")
            })
            output$output_summary <- renderText({
              "Patient classified as Stage I low-risk."
            })
            
        }
        
        if (input$breslowdepth <= 1 & class == "Moderate-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thin_mr_plot.RData")
            })
            output$output_summary <- renderText({
              "Patient classified as Stage I moderate-risk."
            })

        }
        
        if (input$breslowdepth <= 1 & class == "High-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thin_hr_plot.RData")
            })
            output$output_summary <- renderText({
              "Patient classified as Stage I high-risk."
            })

        }
        
        if (input$breslowdepth > 1 & class == "Low-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thick_lr_plot.RData")
            })
            output$output_summary <- renderText({
              "Patient classified as Stage II low-risk."
            })

        }
        
        if (input$breslowdepth > 1 & class == "Moderate-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thick_mr_plot.RData")
            })
            output$output_summary <- renderText({
              "Patient classified as Stage II moderate-risk."
            })

        }
        
        if (input$breslowdepth > 1 & class == "High-Risk"){
            output$class_plot <- renderPlot({
                readRDS("thick_hr_plot.RData")
            })
            
            output$output_summary <- renderText({
              "Patient classified as Stage II high-risk."
            })
        }

    })
  
  output$clinpath_template = downloadHandler(
    filename = function()
    {
      paste0("clinpath_template.csv")
      
    },
    
    content=function(file){
      clin_temp = load("clinpath_template.Rdata")
      write.csv(clin_temp, file)
    }
    
  )
  
  output$clinpath_template2 = downloadHandler(
    filename = function()
    {
      paste0("clinpath_template.csv")
      
    },
    
    content=function(file){
      clin_temp = load("clinpath_template.Rdata")
      write.csv(clin_temp, file)
    }
    
  )
  
  output$ct_template = downloadHandler(
    filename = function()
    {
      paste0("ct_parameter_template.csv")
      
    },
    
    content=function(file){
      ct_temp = load("ct_parameter_template.Rdata")
      write.csv(ct_temp, file)
    }
    
  )
  
  clinpath_data = reactiveVal()
  ct_data = reactiveVal()
  surv_curve = reactiveVal()
  feature_data = reactiveVal()
  fits = reactiveValues()
  plots = reactiveValues()
  
   observeEvent(input$clinpath_input,{
    req(input$clinpath_input)
    clinpath = read.csv(input$clinpath_input$datapath)
    required_clinpath<-c("Age",
                        "Mitotic_Rate",
                        "Breslow_Depth",
                        "Ulceration",
                        "Sex",
                        "FaceHeadNeck",
                        "UpperLimbShoulder",
                        "LowerLimbHip",
                        "Trunk",
                        "Superficial_Spreading",
                        "Nodular",
                        "Lentigo_Maligna",
                        "Acral_Lentiginous",
                        "Desmoplastic")
    if (!all(required_clinpath %in% names(clinpath))){
        showModal(modalDialog(
        title = "Clinpath file error",
        paste0("Clinpath CSV must include all the columns:", paste(required_clinpath,collapse = ", ")),
        easyClose = TRUE,
        footer = NULL))

    } else{
      clinpath_data(clinpath)
    }
  })
   
  observeEvent(input$ct_input,{
    ct = read.csv(input$ct_input$datapath)
    clinpath = clinpath_data()
    required_ct = c("ID","Height",
                      "Skeletal_Muscle_Area",
                      "Subcutaneous_Fat_Area",
                      "Visceral_Fat_Area",
                      "Intramuscular_Fat_Area")
    if (!all(required_ct %in% names(ct)))
            {
              showModal(modalDialog(
              title = "CT file error",
              paste0("CT CSV must include all the columns:", paste(required_ct,collapse = ", ")),
              easyClose = TRUE,
              footer = NULL))
            }
        
    if(nrow(ct) != nrow(clinpath))
            {
              showModal(modalDialog(
              title = "CT file error",
              paste0("CSV files must have same number of rows"),
              easyClose = TRUE,
              footer = NULL))
    } else{
          ct_data(ct)
          }
      
  })
  calculate = observeEvent(input$combined_calc, {
    req(input$clinpath_input)
    withProgress(message = "Calculation in progress", value = 0, {
      
    clinpath = clinpath_data()
    scale <- readRDS("scaling_data.RData")
    class_model <- readRDS("classification_model.RData")
    #glm = readRDS("glm_model.RDATA") #need to make this from the data we get from roswell, nashville, and duke
    class<-c()
    tstages<-c()
    cstages<-c()

    for (i in 1:nrow(clinpath)) {
      row<-clinpath[i, ]
      pt_data<-data.frame(
        Age= row$Age,
        Mitotic_Rate=row$Mitotic_Rate,
        Breslow_Depth = row$Breslow_Depth,
        Ulceration = row$Ulceration,
        Sex = row$Sex,
        FaceHeadNeck = row$FaceHeadNeck,
        UpperLimbShoulder =row$UpperLimbShoulder,
        LowerLimbHip = row$LowerLimbHip,
        Trunk = row$Trunk,
        Superficial_Spreading = row$Superficial_Spreading,
        Nodular = row$Nodular,
        Lentigo_Maligna = row$Lentigo_Maligna,
        Acral_Lentiginous = row$Acral_Lentiginous,
        Desmoplastic = row$Desmoplastic)
        
        if(row$Breslow_Depth<=1.0 )
      {
        if (row$Breslow_Depth<0.8 & row$Ulceration ==0)
        {
          tstage<-"T1a"
          cstage<-"IA"
        }

        if ((row$Breslow_Depth<0.8 & row$Ulceration==1) || (row$Breslow_Depth >=0.8 & row$Breslow_Depth<=1.0))
        {
          tstage<-"T1b"
          cstage<-"IB"
        }

     }

     if (row$Breslow_Depth> 1.0 & row$Breslow_Depth<=2.0)
     {
        tstage<-ifelse (row$Ulceration==0, "T2a","T2b")
        cstage<-ifelse(tstage == "T2a","IB","IIA")

     }

     if (row$Breslow_Depth >2.0 & row$Breslow_Depth<=4.0)
     {
       tstage<-ifelse (row$Ulceration==0, "T3a","T3b")
       cstage<-ifelse(tstage == "T3a","IIA","IIB")
     }




    if (row$Breslow_Depth >4.0 )
    {
      tstage<-ifelse (row$Ulceration==0, "T4a","T4b")
      cstage<-ifelse(tstage == "T4a","IIB","IIC")
    }

    tstages<-c(tstages,tstage)
    cstages<-c(cstages,cstage)
    

    scaled<-predict(scale,pt_data)
      
      
    pred<-as.character(predict(class_model,scaled))
    class<-c(class,pred)
    }
    
    incProgress(1/3)
      

    clinpath$Risk=class
    clinpath$tstages=tstages
    clinpath$cstages=cstages
    
    
    incProgress(1/3)
    
    if(!is.null(input$ct_input$datapath))
      {
      ct = ct_data()
      #clinpath$BCHI = (glm[[1]][1] + glm[[1]][2]*ct$Visceral_Fat/ct$Height^2 + glm[[1]][3]*ct$Skeletal_Muscle_Area/ct$Height^2 +   glm[[1]][4]*ct$Subcutaneous_Fat/ct$Height^2)*ct$Skeletal_Muscle_Area/ct$Intramuscular_Fat
      clinpath$BCHI = (1 + ct$Visceral_Fat/ct$Height^2 + ct$Skeletal_Muscle_Area/ct$Height^2 + ct$Subcutaneous_Fat/ct$Height^2)*ct$Skeletal_Muscle_Area/ct$Intramuscular_Fat
      res.cut <- surv_cutpoint(clinpath, time = "MSS_Time", event = "MSS", variables = c("BCHI"))
      clinpath$combined_risk = NA
      clinpath$combined_risk[clinpath$Risk == "Low-Risk"] = "Low"
      clinpath$combined_risk[clinpath$Risk == "Moderate-Risk" & clinpath$BCHI < res.cut[[1]][[4]][[1]]] = "Med-Low"
      clinpath$combined_risk[clinpath$Risk == "High-Risk" & clinpath$BCHI < res.cut[[1]][[4]][[1]]] = "High-Low"
      clinpath$combined_risk[clinpath$Risk == "Moderate-Risk" & clinpath$BCHI >= res.cut[[1]][[4]][[1]]] = "Med-High"
      clinpath$combined_risk[clinpath$Risk == "High-Risk" & clinpath$BCHI >= res.cut[[1]][[4]][[1]]] = "High-High"
      fit = survfit(Surv(MSS_Time, MSS) ~ combined_risk, clinpath)
      surv_curve(fit)
      } else{
      fit = survfit(Surv(MSS_Time, MSS) ~ Risk, clinpath)
      surv_curve(fit)
      }
    # #pairwise_survdiff(Surv(MSS_Time, MSS) ~ combined_risk, data = clinpath, p.adjust.method = "bonferroni")
    # 
    
    #clinpath <- clinpath[, !grepl("^X(\\.\\d*)?$", names(clinpath))]
    clinpath_data(clinpath)
    incProgress(1/3)
    })
    
  })
  
  output$clin_ct_plot = renderPlot({
    req(length(surv_curve())>0)
    survminer::ggsurvplot(fit = surv_curve(), data = clinpath_data(), risk.table = TRUE, conf.int = FALSE, pval = TRUE)
      })
  
  output$download_combined<-downloadHandler(
    filename = function()
    {
      paste0("melanoma_risk_output",Sys.Date(),".csv")
      
    },
    
    content=function(file)
    {
    validate(need(input$clinpath_input, "No file input"))
    write.csv(clinpath_data(), file, row.names = TRUE)
    })
    
  observeEvent(input$feature_input, {
    req(input$feature_input)
    
    feature = read.csv(input$feature_input$datapath)
    required_feature<-c("Age",
                        "Mitotic_Rate",
                        "Breslow_Depth",
                        "Ulceration",
                        "Sex",
                        "FaceHeadNeck",
                        "UpperLimbShoulder",
                        "LowerLimbHip",
                        "Trunk",
                        "Superficial_Spreading",
                        "Nodular",
                        "Lentigo_Maligna",
                        "Acral_Lentiginous",
                        "Desmoplastic")
    if (!all(required_feature %in% names(feature))){
        showModal(modalDialog(
        title = "Feature file error",
        paste0("Feature CSV must include at least the columns:", paste(required_feature,collapse = ", ")),
        easyClose = TRUE,
        footer = NULL))

    } else{
      feature_data(feature)
    }
  })
  
  observeEvent(input$calc_feature, {
    calc_sig <- function(i, data){

      data$Comparison <- NA
      data$Comparison[data$Group != i] <- "NC"
      data$Comparison[data$Group == i] <- "C"
      if (length(unique(data$Comparison)) > 1){
      logrank <- survdiff(Surv(Met_Time, Mets) ~ Comparison, data = data)
      pval <- logrank$pvalue
      if ((logrank$obs[[1]]/nrow(subset(data, Comparison == "C"))) > (logrank$obs[[2]]/nrow(subset(data, Comparison == "NC")))){
        risk <- "HR"
      }
      if ((logrank$obs[[1]]/nrow(subset(data, Comparison == "C"))) < (logrank$obs[[2]]/nrow(subset(data, Comparison == "NC")))){
      risk <- "LR"
      }
      if ((logrank$obs[[1]]/nrow(subset(data, Comparison == "C"))) == (logrank$obs[[2]]/nrow(subset(data, Comparison == "NC")))){
      risk <- NA
      }
      if (pval < 0.05){
        sig <- "S"
      }
      if (pval >= 0.05){
      sig <- "NS"
      }
      if (logrank$obs[[1]] == 0){
        z <- 1
      }
        if (logrank$obs[[1]] > 0){
        z <- 0
      }
      row <- data.frame("Risk" = risk, "Significance" = sig, "Cluster" = i, "Z" = z)
      return(row)
      }
    }
    
    risk_class = function(data, cluster_sig){
  data$Risk = 1
  data$Risk[data$Group %in% subset(cluster_sig, Risk == "HR" & Significance == "S")$Cluster] = 2
  data$Risk[data$Group %in% subset(cluster_sig, Z == 1)$Cluster] = 0
  return(data)
    }
    
    withProgress(message = "Calculation in progress", value = 0, {
    scale <- readRDS("scaling_data.RData")
    class_model <- readRDS("classification_model.RData")
    class<-c()
    tstages<-c()
    cstages<-c()
    feature = feature_data()
    
    for (i in 1:nrow(feature))
    {
      row<-feature[i, ]
      pt_data<-data.frame(
        Age= row$Age,
        Mitotic_Rate=row$Mitotic_Rate,
        Breslow_Depth = row$Breslow_Depth,
        Ulceration = row$Ulceration,
        Sex = row$Sex,
        FaceHeadNeck = row$FaceHeadNeck,
        UpperLimbShoulder =row$UpperLimbShoulder,
        LowerLimbHip = row$LowerLimbHip,
        Trunk = row$Trunk,
        Superficial_Spreading = row$Superficial_Spreading,
        Nodular = row$Nodular,
        Lentigo_Maligna = row$Lentigo_Maligna,
        Acral_Lentiginous = row$Acral_Lentiginous,
        Desmoplastic = row$Desmoplastic
      )

      scaled<-predict(scale,pt_data)

      pred<-as.character(predict(class_model,scaled))
      class<-c(class,pred)
      if(row$Breslow_Depth<=1.0 )
      {
        if (row$Breslow_Depth<0.8 & row$Ulceration ==0)
        {
          tstage<-"T1a"
          cstage<-"IA"
        }

        if ((row$Breslow_Depth<0.8 & row$Ulceration==1) || (row$Breslow_Depth >=0.8 & row$Breslow_Depth<=1.0))
        {
          tstage<-"T1b"
          cstage<-"IB"
        }

     }

     if (row$Breslow_Depth> 1.0 & row$Breslow_Depth<=2.0)
     {
        tstage<-ifelse (row$Ulceration==0, "T2a","T2b")
        cstage<-ifelse(tstage == "T2a","IB","IIA")

     }

     if (row$Breslow_Depth >2.0 & row$Breslow_Depth<=4.0)
     {
       tstage<-ifelse (row$Ulceration==0, "T3a","T3b")
       cstage<-ifelse(tstage == "T3a","IIA","IIB")
     }




    if (row$Breslow_Depth >4.0 )
    {
      tstage<-ifelse (row$Ulceration==0, "T4a","T4b")
      cstage<-ifelse(tstage == "T4a","IIB","IIC")
    }

    
    
    setProgress(1/4)
      # stage<-ifelse(row$Breslow_Depth<=1,"Stage I","Stage II")
      # stages<-c(stages,stage)
    }
    tstages<-c(tstages,tstage)
    cstages<-c(cstages,cstage)
    
    set.seed(1)
    preProcValues <- preProcess(feature, method = c("center", "scale"))
    data.ml = predict(preProcValues, feature)
    gmm = ClusterR::GMM(data.ml, 25, dist_mode = "eucl_dist", seed_mode = "random_subset", km_iter = 10,
          em_iter = 10, verbose = F)
    pr = predict(gmm, newdata = data.ml)

    feature$Group <- as.factor(pr)
    data.ml$Group = as.factor(pr)

    #calc_sig = load("calc_sig.RData")
    #risk_class = load("risk_class.RData")
    
    setProgress(2/4)
    
    data2 <- data.table::rbindlist(lapply(1:25, calc_sig, feature))
    feature = risk_class(feature, data2)
    
    feature$Before_Risk = class
    feature$Before_Risk = as.numeric(gsub("Low-Risk", 0, gsub("Moderate-Risk", 1, gsub("High-Risk", 2, feature$Before_Risk))))

    X = feature[,-c(ncol(feature), ncol(feature)-1, ncol(feature)-2)]
    feature$tstages=tstages
    feature$cstages=cstages
    feature_data(feature)

    
    setProgress(3/4)
    
    fit_new = xgb.train(params = list(learning_rate = 0.1), data = xgb.DMatrix(data.matrix(X), label = feature$Risk), nrounds =65)
    fit_pred = xgb.train(params = list(learning_rate = 0.1), data = xgb.DMatrix(data.matrix(X), label = feature$Before_Risk), 
                         nrounds = 65)

    shp_new = shapviz(fit_new, data.matrix(X), X)
    shp_pred = shapviz(fit_pred, data.matrix(X), X)

    fits$X = X
    fits$fit_new = fit_new
    fits$fit_pred = fit_pred

    plots$plot1 = sv_importance(shp_new, show_numbers=TRUE)
    plots$plot2 = sv_importance(shp_pred, show_numbers=TRUE)
    plots$plot3 = feature %>%
      mutate(MSS = if_else(MSS == 1, "Dead", "Alive")) %>%
      count(Group, MSS) %>%
      group_by(Group) %>%
      mutate(N = sum(n), p = 100*n/N) %>%
      filter(MSS == "Dead") %>%
      ggplot(aes(x = fct_reorder(Group, p, .desc = TRUE), y = p))+
      geom_col()
    
    setProgress(4/4)
  })

  })

  output$feature_num1 = renderPlot({
    plots$plot1
      })
  output$feature_num2 = renderPlot({
    plots$plot2
      })
  output$cluster_bar = renderPlot({
    plots$plot3
  })
  
  output$confusion1 = renderPrint({
    req(fits$fit_pred)
    xgb_pred = predict(fits$fit_pred, data.matrix(fits$X))
    xgb_pred[xgb_pred>2] = 2
    xgb_pred = round(xgb_pred)

    caret::confusionMatrix(as.factor(xgb_pred), as.factor(feature_data()$Before_Risk))
  })

  output$confusion2 = renderPrint({
    req(fits$fit_new)
    xgb_new = predict(fits$fit_new, data.matrix(fits$X))
    xgb_new[xgb_new>2] = 2
    xgb_new = round(xgb_new)
    
    caret::confusionMatrix(as.factor(xgb_new), as.factor(feature_data()$Risk))
    })

output$download_feature<-downloadHandler(
    filename = function()
    {
      paste0("melanoma_risk_output",Sys.Date(),".csv")

    },

    content=function(file)
    {
    write.csv(feature_data(), file, row.names = TRUE)
    }
)
    
}

# Run the application 
shinyApp(ui = ui, server = server)
```

